# Generated by Django 5.2.3 on 2025-08-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
