# Generated by Django 5.2.3 on 2025-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mark1_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('image6', models.ImageField(upload_to='')),
                ('image7', models.ImageField(upload_to='')),
            ],
        ),
    ]
