# Generated by Django 5.2.3 on 2025-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mark2'),
    ]

    operations = [
        migrations.CreateModel(
            name='poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=100)),
                ('content2', models.CharField(max_length=1000)),
                ('image8', models.ImageField(upload_to='')),
            ],
        ),
    ]
