# Generated by Django 5.2.3 on 2025-08-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_shop_delete_mark2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='mark2',
        ),
    ]
