# Generated by Django 5.2.3 on 2025-09-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_shop_mark2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark1',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='mark1',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='mark1',
            name='image3',
        ),
    ]
