# Generated by Django 5.2.3 on 2025-09-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_image1_mark1_image_remove_mark1_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark2',
            old_name='image4',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='mark2',
            old_name='title1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='mark2',
            name='title6',
        ),
    ]
